coreels/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('user.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('reel.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reel/urls.py
"""Module containing URL partterns for our reel app"""

from django.urls import path

from reel import views
from .views import IndexView, CreateVideo, VideoDetail, UpdateVideo, DeleteVideo, about

urlpatterns = [
    path('', IndexView.as_view(), name='home'),
    path('create/', CreateVideo.as_view(), name='upload'),
    path('<int:pk>/', VideoDetail.as_view(), name='video-detail'),
    path('<int:pk>/update/', UpdateVideo.as_view(), name='update-video'),
    path('<int:pk>/delete/', DeleteVideo.as_view(), name='delete-video'),
    path('explore/', views.explore, name='explore'),
    path('team/', views.team, name='team'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('faqs/', views.faqs, name='faqs'),
]

reel/models.py
from distutils.util import convert_path
from django.db import models
from django.conf import settings
from django.core.validators import FileExtensionValidator
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class Category(models.Model):
    """Represents each movie category"""

    name = models.CharField(
        _("category title"), max_length=155,
        help_text=_("enter short caegory name")
    )
    description = models.TextField(
        _("long description"), help_text=_("long category description")
    )
    date = models.DateTimeField(
        _("date added"), default=timezone.now,
        help_text="date category was created"
    )

    class Meta:
        ordering = ['-date', 'name']
        verbose_name_plural = 'categories'

    def __str__(self) -> str:
        return self.name


class Reel(models.Model):
    """Represents each reel/short video in collection"""
    uploader = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name=_("uploaded by"),
        on_delete=models.CASCADE
    )
    title = models.CharField(
        _("video title"), max_length=255,
        help_text=_("Enter a title for your short video")
    )
    description = models.TextField(
        _("long description"),
        help_text=_("Enter a description for your short video")
    )
    category = models.ManyToManyField(
        Category, verbose_name=_("video category"),
        help_text=_("choose a category for your short video")
    )
    cover_thumbnail = models.FileField(
        _("video cover"), upload_to="reels/cover", help_text=_("cover image"),
        null=True, blank=True, validators=[
            FileExtensionValidator(allowed_extensions=['jpg','jpeg','png'])
        ]
    )
    video = models.FileField(
        _("video file"), upload_to='reels', max_length=100,
        help_text=_("upload short video file less than 15 minutes"),
        validators=[FileExtensionValidator(allowed_extensions=[
            'MOV', 'avi', 'mp4', 'webm', 'mkv'
        ])]
    )
    published = models.BooleanField(
        _("published status"), default=False,
        help_text=_("Designates whether video has been published."),
    )
    date_posted = models.DateTimeField(
        _("date uploaded"), default=timezone.now,
        help_text="date video was uploaded"
    )

    class Meta:
        ordering = ['-date_posted', 'title']

    def __str__(self) -> str:
        return self.title

    def get_categories(self):
        """Returns categories of a given reel."""


class Comment(models.Model):
    """Represents comment made on a reel"""

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name=_("commented by"),
        on_delete=models.CASCADE, related_name="commenter"
    )
    comment = models.TextField(
        help_text=_("comment on reels")
    )
    real = models.ForeignKey(
        Reel, verbose_name=_("comment on"), on_delete=models.CASCADE,
        help_text=_("reel commented on"), related_name="commented"
    )
    date = models.DateTimeField(
        _("date commented"), default=timezone.now,
        help_text="date comment was made"
    )

    class Meta:
        ordering = ['-date', 'user']

    def __str__(self) -> str:
        return f"{self.user} commented on: {self.real}"


class Favorite(models.Model):
    """Represents favorite made on a reel"""

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name=_("favorited by"),
        on_delete=models.CASCADE, related_name="favoriter"
    )
    real = models.ForeignKey(
        Reel, verbose_name=_("favorite on"), on_delete=models.CASCADE,
        help_text=_("reel being favorited"), related_name="favoriited"
    )
    date = models.DateTimeField(
        _("date favorited"), default=timezone.now,
        help_text="date favorite was added"
    )

    class Meta:
        ordering = ['-date', 'user']

    def __str__(self) -> str:
        return f"{self.user} favorited: {self.real}"


class Like(models.Model):
    """Represents like made on a reel"""

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name=_("liked by"),
        on_delete=models.CASCADE, related_name="liker"
    )
    real = models.ForeignKey(
        Reel, verbose_name=_("liked reel"), on_delete=models.CASCADE,
        help_text=_("reel liked"), related_name="liked"
    )
    date = models.DateTimeField(
        _("date liked"), default=timezone.now,
        help_text="date like was recorded"
    )

    class Meta:
        ordering = ['-date', 'user']

    def __str__(self) -> str:
        return f"{self.user} liked: {self.real}"


class Dislike(models.Model):
    """Represents dislike made on a reel"""

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name=_("disliked by"),
        on_delete=models.CASCADE, related_name="disliker"
    )
    real = models.ForeignKey(
        Reel, verbose_name=_("disliked reel"), on_delete=models.CASCADE,
        help_text=_("reel disliked"), related_name="disliked"
    )
    date = models.DateTimeField(
        _("date disliked"), default=timezone.now,
        help_text="date dislike was recorded"
    )

    class Meta:
        ordering = ['-date', 'user']

    def __str__(self) -> str:
        return f"{self.user} disliked: {self.real}"


class View(models.Model):
    """Represents view made on a reel"""

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name=_("viewed by"),
        on_delete=models.CASCADE, related_name="viewer"
    )
    real = models.ForeignKey(
        Reel, verbose_name=_("viewed reel"), on_delete=models.CASCADE,
        help_text=_("reel viewed")
    )
    date = models.DateTimeField(
        _("date viewed"), default=timezone.now,
        help_text="date view was made"
    )

    class Meta:
        ordering = ['-date', 'user']

    def __str__(self) -> str:
        return f"{self.user} viewed: {self.real}"

reel/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.exceptions import ValidationError
from django.shortcuts import render, reverse
from django.views.generic import TemplateView
from django.views.generic import (
    CreateView, DeleteView, DetailView, ListView, UpdateView
)
from django.utils.translation import gettext_lazy as _

from .models import Reel


class IndexView(ListView):
    model = Reel
    context_object_name = "reels"
    template_name = "reel/home.html"
    order_by = "-date_posted"


# Restricting the create video page to only logged in users
class CreateVideo(LoginRequiredMixin, CreateView):
    model = Reel
    fields = [
        'video'
    ]
    template_name = "reel/upload.html"

    def form_valid(self, form):
        if self.request.user.is_verified: # Is user a verified college student?
            form.instance.uploader = self.request.user
            return super().form_valid(form)
        
        # If user is not verified.
        form.add_error(None, ValidationError(
            _("Only verified college students can upload videos"),
            code='user_error'
        ))
        return render(self.request, self.template_name, {'form': form})

    def get_success_url(self):
        return reverse('update-video', kwargs={'pk': self.object.pk})


class VideoDetail(DetailView):
    model = Reel
    context_object_name = 'reel'
    template_name = "reel/player.html"

# Restricting the update video page to only logged in users
class UpdateVideo(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Reel
    fields = [
        'title', 'description', 'category', 'cover_thumbnail', 'published'
    ]
    template_name = "reel/update-reel.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['reel'] = self.get_object()
        return context

    def get_success_url(self):
        return reverse('video-detail', kwargs={'pk': self.object.pk})

    def test_func(self):
        video = self.get_object()
        return self.request.user == video.uploader

# Restricting the delete video page to only logged in users
class DeleteVideo(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Reel
    template_name = "delete_video.html"

    def get_success_url(self):
        return reverse("index")

    def test_func(self):
        video = self.get_object()
        return self.request.user == video.uploader


def explore(request):
    """Returns explore page"""
    reels = Reel.objects.all()
    return render(request, 'reel/explore.html', {'reels': reels})


def team(request):
    """Returns team page"""
    return render(request, 'reel/team.html', {})


def about(request):
    """Returns about page"""
    return render(request, 'reel/about.html', {})


def contact(request):
    """Returns contact page"""
    return render(request, 'reel/contact.html', {})


def faqs(request):
    """Returns FAQS page"""
    return render(request, 'reel/faqs.html', {})

reel/templates/reel/about.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>About Coreels</title>
{% endblock title %}

{% block content %}
<!-- About page START -->
<main class="main">
    <section class="members section">
      <div class="section-title">
        <h2 class="title">About Coreels</h2>
      </div>
    </section>
</main>
<!-- About page END -->
{% endblock content %}

reel/templates/reel/contact.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>About Coreels</title>
{% endblock title %}

{% block content %}
<!-- Contact page START -->
<main class="main">
    <section class="members section">
      <div class="section-title">
        <h2 class="title">Contact Coreels</h2>
      </div>
    </section>
</main>
<!-- Contact page END -->
{% endblock content %}

reel/templates/reel/explore.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css %}
<script src="https://kit.fontawesome.com/ed99df9468.js" crossorigin="anonymous"></script>
<link rel="stylesheet" href="{% static 'css/explore.css' %}" />
{% endblock extra_css %}

{% block title %}
<title>Explore Coreels Movie Collections</title>
{% endblock title %}

{% block content %}
<!-- Explore page START -->
<main class="explore-main">
    <article class="explore-header--center">
      <div class="explore-center">
        <div></div>
        <div class="explore-header mobile-explore-header">
          <div class="mobile-explore-user">
            <div>
              <div class="notify-bell">
                <span class="icon-color">
                  <i class="fa-regular fa-bell fa-2x"></i>
                </span>
              </div>
            </div>

            <div class="user-info-cont">
              <div class="user-profile-cont">
                <div class="user-image-cont">
                  <img
                    src="{% static 'images/user-image.svg' %}"
                    alt="user profile image"
                    class="user-image"
                  />
                </div>
                <div class="user-name">
                  <h6>Daniel Amir</h6>
                </div>
                <div class="profile-button">
                  <button class="arrow down-button">
                    <img
                      src="{% static 'images/icon-arrow-down.svg' %}"
                      alt="arrow-down"
                      class="arrow-button"
                    />
                  </button>
                  <ul class="user-sidebar user-sidebar-toggle">
                    <a href="#"><li class="user-links">Following</li></a>
                    <a href="#"><li class="user-links">My playlist</li></a>
                    <a href="#"><li class="user-links">Watch later</li></a>
                    <a href="#"><li class="user-links">Downloads</li></a>
                    <a href="#"><li class="user-links">Profile settings</li></a>
                    <a href="#"><li class="user-links">Sign out</li></a>
                  </ul>
                </div>
              </div>
            </div>
          </div>
  
          <div class="form-explore">
            <div class="form-cont form-cont-big">
              <form action="" class="form-group">
                <input
                  type="text"
                  name="search"
                  class="explore-search"
                  id="search-button"
                  required
                  placeholder="search here"
                />
                <input
                  type="text"
                  name="search"
                  class="explore-search-big"
                  id="search-button"
                  required
                  placeholder="search for songs, lyrics, artist..."
                />
              </form>
              <div class="small-search-icon">
                <img src="{% static 'images/filter-small.svg' %}" alt="filter" />
              </div>
              <div class="big-search-icon">
                <img src="{% static 'images/filter.svg' %}" alt="filter" />
              </div>
            </div>
            <div class="mobile-explore-user-big">
              <div>
                <div class="notify-bell">
                  <span class="icon-color">
                    <i class="fa-regular fa-bell fa-2x"></i>
                  </span>
                </div>
              </div>
  
              <div class="user-info-cont">
                <div class="user-profile-cont">
                  <div class="user-image-cont">
                    <img
                      src="{% static 'images/user-image.svg' %}"
                      alt="user profile image"
                      class="user-image"
                    />
                  </div>
                  <div class="user-name">
                    <h6>Daniel Amir</h6>
                  </div>
                  <div class="profile-button">
                    <button class="arrow down-button">
                      <img
                        src="{% static 'images/icon-arrow-down.svg' %}"
                        alt="arrow-down"
                        class="arrow-button"
                      />
                    </button>
                    <ul class="user-sidebar user-sidebar-toggle">
                      <a href="#"><li class="user-links">Following</li></a>
                      <a href="#"><li class="user-links">My playlist</li></a>
                      <a href="#"><li class="user-links">Watch later</li></a>
                      <a href="#"><li class="user-links">Downloads</li></a>
                      <a href="#"><li class="user-links">Profile settings</li></a>
                      <a href="#"><li class="user-links">Sign out</li></a>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </article>
    <article class="explore-tag-center-header">
      <div class="content">
        <div class="explore-tag-center">
          <div class="tag-button">
            <a href="#"><button class="explore-tags">Art gallery</button></a>
          </div>
          <div class="tag-button small-explore-tag">
            <a href="#"><button class="explore-tags">Science & tech</button></a>
          </div>
          <div class="tag-button">
            <a href="#"><button class="explore-tags">campaign</button></a>
          </div>
          <div class="tag-button small-explore-tag">
            <a href="#"><button class="explore-tags">campaign</button></a>
          </div>
          <div class="tag-button small-explore-tag">
            <a href="#"><button class="explore-tags">documentaries</button></a>
          </div>
          <div class="tag-button small-explore-tag">
            <a href="#"><button class="explore-tags">fashion</button></a>
          </div>
        </div>
      </div>
    </article>
    <section class="explore-landing-page">
      <div class="explore-landing-center">
        <div class="explore-section-center">

          <!-- Auto video start -->
          {% for reel in reels %}
          <article class="explore-card-design">
            <div class="explore-video-container">
              <a href="{% url 'video-detail' reel.pk %}">
                <img src="{{ reel.cover_thumbnail.url }}" alt="" class="trendy" />
              </a>
            </div>
            <h4 class="explore-card-title">{{ reel.title }}</h4>
            <p class="explore-card-info">By: {{ reel.uploader.full_name }}</p>
          </article>
          {% endfor %}

          <article class="explore-card-design">
            <div class="explore-video-container">
              <img src="{% static 'images/reading.png' %}" alt="" class="trendy" />
            </div>
            <h4 class="explore-card-title">Reading habits</h4>
            <p class="explore-card-info">By: Jemimah Ameobi</p>
          </article>
          <article class="explore-card-design">
            <div class="explore-video-container">
              <img src="{% static 'images/reading.png' %}" alt="" class="trendy" />
            </div>
            <h4 class="explore-card-title">Reading habits</h4>
            <p class="explore-card-info">By: Jemimah Ameobi</p>
          </article>
          <article class="explore-card-design">
            <div class="explore-video-container">
              <img src="{% static 'images/reading.png' %}" alt="" class="trendy" />
            </div>
            <h4 class="explore-card-title">Reading habits</h4>
            <p class="explore-card-info">By: Jemimah Ameobi</p>
          </article>
          <article class="explore-card-design">
            <div class="explore-video-container">
              <img src="{% static 'images/reading.png' %}" alt="" class="trendy" />
            </div>
            <h4 class="explore-card-title">Reading habits</h4>
            <p class="explore-card-info">By: Jemimah Ameobi</p>
          </article>
          <article class="explore-card-design">
            <div class="explore-video-container">
              <img src="{% static 'images/reading.png' %}" alt="" class="trendy" />
            </div>
            <h4 class="explore-card-title">Reading habits</h4>
            <p class="explore-card-info">By: Jemimah Ameobi</p>
          </article>
          <article class="explore-card-design">
            <div class="explore-video-container">
              <img src="{% static 'images/reading.png' %}" alt="" class="trendy" />
            </div>
            <h4 class="explore-card-title">Reading habits</h4>
            <p class="explore-card-info">By: Jemimah Ameobi</p>
          </article>
          <article class="explore-card-design">
            <div class="explore-video-container">
              <img src="{% static 'images/reading.png' %}" alt="" class="trendy" />
            </div>
            <h4 class="explore-card-title">Reading habits</h4>
            <p class="explore-card-info">By: Jemimah Ameobi</p>
          </article>
          <article class="explore-card-design">
            <div class="explore-video-container">
              <img src="{% static 'images/reading.png' %}" alt="" class="trendy" />
            </div>
            <h4 class="explore-card-title">Reading habits</h4>
            <p class="explore-card-info">By: Jemimah Ameobi</p>
          </article>
          <article class="explore-card-design">
            <div class="explore-video-container">
              <img src="{% static 'images/reading.png' %}" alt="" class="trendy" />
            </div>
            <h4 class="explore-card-title">Reading habits</h4>
            <p class="explore-card-info">By: Jemimah Ameobi</p>
          </article>
          <article class="explore-card-design">
            <div class="explore-video-container">
              <img src="{% static 'images/reading.png' %}" alt="" class="trendy" />
            </div>
            <h4 class="explore-card-title">Reading habits</h4>
            <p class="explore-card-info">By: Jemimah Ameobi</p>
          </article>
          <article class="explore-card-design">
            <div class="explore-video-container">
              <img src="{% static 'images/reading.png' %}" alt="" class="trendy" />
            </div>
            <h4 class="explore-card-title">Reading habits</h4>
            <p class="explore-card-info">By: Jemimah Ameobi</p>
          </article>
          <article class="explore-card-design">
            <div class="explore-video-container">
              <img src="{% static 'images/reading.png' %}" alt="" class="trendy" />
            </div>
            <h4 class="explore-card-title">Reading habits</h4>
            <p class="explore-card-info">By: Jemimah Ameobi</p>
          </article>
        </div>
      </div>
    </section>
    <section class="explore-trending-section">
      <div class="explore-trending-section-center">
        <div class="explore-title-button">
          <div class="section-title explore-sec"><h2>New releases</h2></div>
          <div>
            <a href="./trending.html"
              ><button class="explore-button home-buttons">See more</button></a
            >
          </div>
        </div>
      </div>
    </section>
  </main>
<!-- Explore page END -->
{% endblock content %}

reel/templates/reel/faqs.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Frequently Asked Questions About Coreels</title>
{% endblock title %}

{% block content %}
<!-- About page START -->
<main class="main">
    <section class="members section">
      <div class="section-title">
        <h2 class="title">Frequently Asked Questions</h2>
      </div>
    </section>
</main>
<!-- About page END -->
{% endblock content %}

reel/templates/reel/team.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Coreels Team Members</title>
{% endblock title %}

{% block content %}
<!-- Team page START -->
<main class="main">
    <section class="members section">
      <div class="section-title">
        <h2 class="title">Meet our team</h2>
      </div>
      <div class="leader-container">
        <div class="lead-image-container">
          <img src="{% static 'images/image-one.png' %}" alt="image one" class="leader" />
        </div>
        <div class="lead">
          <div></div>
          <div>
            <h3 class="lead-name">Jemima Ameobi</h3>
            <p class="lead-title">Team Leader</p>
            <p class="phone">000000000000 / Jemmy34@gmail.com</p>
          </div>
        </div>
      </div>
      <p class="team-des">
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eligendi
        mollitia aspernatur assumenda iste nihil expedita tenetur debitis, dolor
        eum optio adipisci ullam nemo soluta temporibus pariatur velit iure, ex
        delectus!
      </p>
      <h2 class="small-title">Team members</h2>
  
      <div class="team-center">
        <div class="team-member">
          <div class="member-cont">
            <img
              src="{% static 'images/image-two.png' %}"
              alt="member name"
              class="member-image"
            />
          </div>
          <h5 class="member-name">Ajao Jelili</h5>
          <p class="member-title">UX Designer</p>
        </div>
        <div class="team-member">
          <div class="member-cont">
            <img
              src="{% static 'images/image-two.png' %}"
              alt="member name"
              class="member-image"
            />
          </div>
          <h5 class="member-name">Ajao Jelili</h5>
          <p class="member-title">UX Designer</p>
        </div>
        <div class="team-member">
          <div class="member-cont">
            <img
              src="{% static 'images/image-two.png' %}"
              alt="member name"
              class="member-image"
            />
          </div>
          <h5 class="member-name">Ajao Jelili</h5>
          <p class="member-title">UX Designer</p>
        </div>
        <div class="team-member">
          <div class="member-cont">
            <img
              src="{% static 'images/image-two.png' %}"
              alt="member name"
              class="member-image"
            />
          </div>
          <h5 class="member-name">Ajao Jelili</h5>
          <p class="member-title">UX Designer</p>
        </div>
        <div class="team-member">
          <div class="member-cont">
            <img
              src="{% static 'images/image-two.png' %}"
              alt="member name"
              class="member-image"
            />
          </div>
          <h5 class="member-name">Ajao Jelili</h5>
          <p class="member-title">UX Designer</p>
        </div>
        <div class="team-member">
          <div class="member-cont">
            <img
              src="{% static 'images/image-two.png' %}"
              alt="member name"
              class="member-image"
            />
          </div>
          <h5 class="member-name">Ajao Jelili</h5>
          <p class="member-title">UX Designer</p>
        </div>
  
        <div class="team-member">
          <div class="member-cont">
            <img
              src="{% static 'images/image-two.png' %}"
              alt="member name"
              class="member-image"
            />
          </div>
          <h5 class="member-name">Ajao Jelili</h5>
          <p class="member-title">UX Designer</p>
        </div>
        <div class="team-member">
          <div class="member-cont">
            <img
              src="{% static 'images/image-two.png' %}"
              alt="member name"
              class="member-image"
            />
          </div>
          <h5 class="member-name">Ajao Jelili</h5>
          <p class="member-title">UX Designer</p>
        </div>
      </div>
    </section>
</main>
<!-- Team page END -->
{% endblock content %}

reel/templates/reel/update-reel.html
{% extends 'base.html' %}
{% load static reel_tags %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/signup.css' %}" />
<link rel="stylesheet" href="{% static 'css/update.css' %}" />
{% endblock extra_css %}

{% block title %}
<title>Update Reel</title>
{% endblock title %}

{% block content %}
<!-- Upadte Form START -->
<main class="signup-page">
  <div class="row">
    <div class="reel-update">
      <form action="{% url 'account_signup' %}" method="post" class="form--login" enctype="multipart/form-data" name="uploadForm">
          <h1>Update reel</h1>
          {% if form.non_field_errors %}
          <div class="non-field-errors">
            <ul class="errorlist">
                {% for error in form.non_field_errors %}
                <li>
                    <strong>{{ error|escape }}</strong>
                </li>
                {% endfor %}
            </ul>
          </div>
          {% endif %}
          {% csrf_token %}

          <label for="id_title">Video title</label>
          <input type="text" placeholder="Video short title" name="title" maxlength="255" required id="id_title" class="input--border" spellcheck="false" data-ms-editor="true" value="{{ form.title.value|stringformat:'s' }}">
          <div class="input-error">
            {{ form.title.errors }}
          </div>

          <label for="id_description">Detailed description</label>
          <textarea name="description" id="id_description" class="input--border" required spellcheck="false" data-ms-editor="true" placeholder="Enter detailed video description" rows="25">{{ form.description.value|stringformat:'s' }}</textarea>
          <div class="input-error">
            {{ form.description.errors }}
          </div>

          <label for="id_category">Video category</label>
          <select name="category" required="" id="id_category" class="input--border" multiple="">
            {% get_category_options %}
          </select>
          <div class="input-error">
            {{ form.category.errors }}
          </div>

          <label for="id_cover_thumbnail">Video cover</label>
          <input type="file" name="cover_thumbnail" id="id_cover_thumbnail" class="input--border" accept="image/*">
          <div class="input-error">
            {{ form.cover_thumbnail.errors }}
          </div>

          <label for="id_published">
            <input type="checkbox" name="published" id="id_published" class="input--border">
            Published status
          </label>
          <div class="input-error">
            {{ form.published.errors }}
          </div>
      
          <button class="signup--button">Publish Reel</button>
      </form>
    </div>
    <div class="reel-preview">
      <h2>Video preview</h2>
      <video width="100%" height="auto" controls>
        <source src="{{ reel.video.url }}" type="video/mp4">
        Your browser does not support the video tag.
      </video>
    </div>
  </div>
</main>
<!-- Register Form END -->
{% endblock content %}